api_keys:
  openai_api_key: ${OPENAI_API_KEY}
  google_api_key: ${GOOGLE_API_KEY}
  google_cse_id: ${GOOGLE_CSE_ID}
  huggingface_token: ${HUGGINGFACE_TOKEN}

# Model Configuration
models:
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  cross_encoder_model: "cross-encoder/ms-marco-electra-base"
  llm_model: "gpt-4o" # Or any OpenAI API compatible LLM

# Cache Configuration
cache:
  ttl_days: 30
  memory_size: 50
  similarity_threshold: 0.85
  base_dir: "/tmp/rag_cache"

# Search Parameters
search:
  num_results_trusted: 6
  num_results_general: 4
  num_results_youtube: 3
  timeout_seconds: 8
  max_content_length: 2500
  chunk_size: 800
  chunk_overlap: 150

# Trusted Domains
trusted_domains:
  sports_medicine:
    - "sportsmed.org"
    - "bjsm.bmj.com"
    - "sportsmedicine.stanford.edu"
    - "hopkinsmedicine.org"
    - "med.stanford.edu/sports"
    - "mayoclinic.org"
    - "health.harvard.edu"
    - "my.clevelandclinic.org"

  athletic_resources:
    - "acsm.org"
    - "jospt.org"
    - "gssiweb.org"
    - "acewebcontent.azureedge.net"
    - "hopkinsmedicine.org/sports-medicine"
    - "hss.edu"
    - "stopsportsinjuries.org"
    - "teamusa.org"
    - "ncaa.org/sports-science"
    - "strengthandconditioning.org"
    - "scienceforsport.com"
    - "sportscienceinsider.com"
    - "medlineplus.gov"

  research_sources:
    - "pubmed.ncbi.nlm.nih.gov"
    - "journals.humankinetics.com"

# Response Generation
response:
  max_tokens: 400
  temperature: 0.7
  retrieval_k: 3

# YouTube Integration
youtube:
  relevance_threshold: 0.5
  prioritize_instructional: true
  filter_patterns:
    - "how to"
    - "tutorial"
    - "guide"
    - "tips"
    - "technique"
